# Nome do workflow
name: Deploy API to Azure VM

# Gatilho
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # 3. Make mvnw executable
      - name: Make mvnw executable
        run: chmod +x ./mvnw

      # 4. Build - Gera o app.jar dentro da pasta target
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # 5. Copy - Copia a pasta target inteira para o servidor
      - name: Copy build artifacts to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target" # Copia a pasta target inteira
          target: "/opt/routehelper-api/"

      # 6. Restart - Adaptado para rodar de dentro da pasta target
      - name: Restart API Service on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Procura pelo processo Java rodando DE DENTRO da pasta target
            PID=$(ps -ef | grep '/opt/routehelper-api/target/app.jar' | grep -v grep | awk '{print $2}')
            
            if [ -n "$PID" ]; then
              echo "Stopping old API process with PID: $PID"
              sudo kill $PID
              sleep 5
            fi
            
            echo "Starting new API process from within the target directory"
            # Navega para DENTRO da pasta target
            cd /opt/routehelper-api/target/
            # Inicia a API a partir daqui
            nohup java -jar app.jar &