# Nome do workflow
name: Deploy API to Azure VM

# Gatilho
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # 3. Make mvnw executable
      - name: Make mvnw executable
        run: chmod +x ./mvnw

      # 4. Build
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # 5. Copy (SIMPLIFICADO)
      # Copia o app.jar diretamente da pasta target do robô para o servidor
      - name: Copy JAR to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/app.jar" # <-- MUDANÇA PRINCIPAL
          target: "/opt/routehelper-api/"

      # 6. Restart
      - name: Restart API Service on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PID=$(ps -ef | grep '/opt/routehelper-api/app.jar' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              echo "Stopping old API process with PID: $PID"
              sudo kill $PID
              sleep 5
            fi
            
            echo "Starting new API process with app.jar"
            cd /opt/routehelper-api/
            nohup java -jar app.jar &